### ISSUE TITLE
Still not working with TRV

### ISSUE THREAD

**Issue by sandrodiscandicci** [mario-peters/ShellyCloudPlugin#8]
Sorry but I've done update but is still not working. I've the same errors on domoticz.
2022-01-23 19:15:49.711 Error: (RadiatoreCamera) 'onHeartbeat' failed 'KeyError'.
2022-01-23 19:15:49.711 Error: (RadiatoreCamera) ----> Line 320 in '/home/pi/domoticz/plugins/ShellyCloudPlugin/plugin.py', function onHeartbeat
2022-01-23 19:15:49.711 Error: (RadiatoreCamera) ----> Line 285 in '/home/pi/domoticz/plugins/ShellyCloudPlugin/plugin.py', function onHeartbeat
2022-01-23 19:15:49.711 Error: (RadiatoreCamera) ----> Line 655 in '/home/pi/domoticz/plugins/ShellyCloudPlugin/plugin.py', function updateTRV
I send too outcome of status.
{"wifi_sta":{"connected":true,"ssid":"casamimmi","ip":"172.17.1.134","rssi":-78},"cloud":{"enabled":true,"connected":true},"mqtt":{"connected":false},"time":"19:16","unixtime":1642961791,"serial":35,"has_update":false,"mac":"60A423D3E9F2","cfg_changed_cnt":0,"actions_stats":{"skipped":0},"thermostats":[{"pos":100.0,"target_t":{"enabled":true,"value":23.0,"units":"C"},"tmp":{"value":19.7,"units":"C","is_valid":true},"schedule":false,"schedule_profile":0}],"calibrated":true,"bat":{"value":100,"voltage":4.136},"charger":false,"update":{"status":"unknown","has_update":false,"new_version":"20220115-083921/v2.1.2@3f3e56f8","old_version":"20220115-083921/v2.1.2@3f3e56f8","beta_version":null},"ram_total":97280,"ram_free":22488,"fs_size":65536,"fs_free":59508,"uptime":93011,"fw_info":{"device":"shellytrv-60A423D3E9F2","fw":"20220115-083921/v2.1.2@3f3e56f8"},"ps_mode":0,"dbg_flags":0}
Thank you for your support.

**Comment by mario-peters** [comment]
I think I'have found the issue in the TRV, but for some reason updating the shelly relays doesn't work anymore. I have to fix this issue before committing the solution for your bug. A little more patients please. :-)

**Comment by sandrodiscandicci** [comment]
No problems. Thank you for all.

**Comment by mario-peters** [comment]
I think it is fixed.
Just committed the new source code.
Could you please test it and let me know if it works?

**Comment by mario-peters** [comment]
could you please let me know if you tested the new code.
If it works fine, then I can close this bug.

**Comment by sandrodiscandicci** [comment]
I've tester but still not work. I'll send outcome ASAP. Thank you for all 

Il 28 gennaio 2022 08:26:17 CET, mario-peters ***@***.***> ha scritto:
>could you please let me know if you tested the new code.
>If it works fine, then I can close this bug.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/mario-peters/ShellyCloudPlugin/issues/8#issuecomment-1023953318
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Inviato dal mio dispositivo Android con K-9 Mail. Perdonate la brevità.

**Comment by sandrodiscandicci** [comment]
This is the outcome after upgrading.
2022-01-28 16:47:43.588 Error: (Radiatore_Camera) 'onStart' failed 'AttributeError'.
2022-01-28 16:47:43.588 Error: (Radiatore_Camera) ----> Line 300 in '/home/pi/domoticz/plugins/ShellyCloudPlugin/plugin.py', function onStart
2022-01-28 16:47:43.588 Error: (Radiatore_Camera) ----> Line 115 in '/home/pi/domoticz/plugins/ShellyCloudPlugin/plugin.py', function onStart
2022-01-28 16:47:43.588 Error: (Radiatore_Camera) ----> Line 364 in '/home/pi/domoticz/plugins/ShellyCloudPlugin/plugin.py', function createTRV
2022-01-28 16:47:53.686 Error: (Radiatore_Camera) 'onHeartbeat' failed 'KeyError'.
2022-01-28 16:47:53.686 Error: (Radiatore_Camera) ----> Line 328 in '/home/pi/domoticz/plugins/ShellyCloudPlugin/plugin.py', function onHeartbeat
2022-01-28 16:47:53.686 Error: (Radiatore_Camera) ----> Line 293 in '/home/pi/domoticz/plugins/ShellyCloudPlugin/plugin.py', function onHeartbeat
2022-01-28 16:47:53.686 Error: (Radiatore_Camera) ----> Line 663 in '/home/pi/domoticz/plugins/ShellyCloudPlugin/plugin.py', function updateTRV

**Comment by mario-peters** [comment]
When did you updated the source code?
In the latest version of today I fixed 2 other issues.
1 of them is in the update functionality of the TRV.

if you have the latest source code, have your removed the TRV in the hardware screen and did you create a new one (after updating to the latest version of the source code?

**Comment by sandrodiscandicci** [comment]
I have now downloaded your latest release. I removed the TRV and tried to recreate the hardware again. These are the error messages.
2022-01-28 21:03:33.452 Error: (RadiatoreCamera) 'onStart' failed 'ConnectionError'.
2022-01-28 21:03:33.452 Error: (RadiatoreCamera) ----> Line 313 in '/home/pi/domoticz/plugins/ShellyCloudPlugin/plugin.py', function onStart
2022-01-28 21:03:33.452 Error: (RadiatoreCamera) ----> Line 119 in '/home/pi/domoticz/plugins/ShellyCloudPlugin/plugin.py', function onStart
2022-01-28 21:03:33.452 Error: (RadiatoreCamera) ----> Line 75 in '/usr/lib/python3/dist-packages/requests/api.py', function get
2022-01-28 21:03:33.452 Error: (RadiatoreCamera) ----> Line 60 in '/usr/lib/python3/dist-packages/requests/api.py', function request
2022-01-28 21:03:33.452 Error: (RadiatoreCamera) ----> Line 533 in '/usr/lib/python3/dist-packages/requests/sessions.py', function request
2022-01-28 21:03:33.452 Error: (RadiatoreCamera) ----> Line 646 in '/usr/lib/python3/dist-packages/requests/sessions.py', function send
2022-01-28 21:03:33.452 Error: (RadiatoreCamera) ----> Line 516 in '/usr/lib/python3/dist-packages/requests/adapters.py', function send
2022-01-28 21:03:46.092 Error: (RadiatoreCamera) 'onHeartbeat' failed 'ConnectionError'.
2022-01-28 21:03:46.092 Error: (RadiatoreCamera) ----> Line 341 in '/home/pi/domoticz/plugins/ShellyCloudPlugin/plugin.py', function onHeartbeat
2022-01-28 21:03:46.092 Error: (RadiatoreCamera) ----> Line 306 in '/home/pi/domoticz/plugins/ShellyCloudPlugin/plugin.py', function onHeartbeat
2022-01-28 21:03:46.092 Error: (RadiatoreCamera) ----> Line 75 in '/usr/lib/python3/dist-packages/requests/api.py', function get
2022-01-28 21:03:46.092 Error: (RadiatoreCamera) ----> Line 60 in '/usr/lib/python3/dist-packages/requests/api.py', function request
2022-01-28 21:03:46.092 Error: (RadiatoreCamera) ----> Line 533 in '/usr/lib/python3/dist-packages/requests/sessions.py', function request
2022-01-28 21:03:46.092 Error: (RadiatoreCamera) ----> Line 646 in '/usr/lib/python3/dist-packages/requests/sessions.py', function send
2022-01-28 21:03:46.092 Error: (RadiatoreCamera) ----> Line 516 in '/usr/lib/python3/dist-packages/requests/adapters.py', function send
2022-01-28 21:04:17.415 Error: (RadiatoreCamera) 'onHeartbeat' failed 'KeyError'.
2022-01-28 21:04:17.415 Error: (RadiatoreCamera) ----> Line 341 in '/home/pi/domoticz/plugins/ShellyCloudPlugin/plugin.py', function onHeartbeat
2022-01-28 21:04:17.415 Error: (RadiatoreCamera) ----> Line 306 in '/home/pi/domoticz/plugins/ShellyCloudPlugin/plugin.py', function onHeartbeat
2022-01-28 21:04:17.415 Error: (RadiatoreCamera) ----> Line 712 in '/home/pi/domoticz/plugins/ShellyCloudPlugin/plugin.py', function updateTRV
2022-01-28 21:04:47.480 Error: (RadiatoreCamera) 'onHeartbeat' failed 'KeyError'.
2022-01-28 21:04:47.480 Error: (RadiatoreCamera) ----> Line 341 in '/home/pi/domoticz/plugins/ShellyCloudPlugin/plugin.py', function onHeartbeat
2022-01-28 21:04:47.480 Error: (RadiatoreCamera) ----> Line 306 in '/home/pi/domoticz/plugins/ShellyCloudPlugin/plugin.py', function onHeartbeat
2022-01-28 21:04:47.480 Error: (RadiatoreCamera) ----> Line 712 in '/home/pi/domoticz/plugins/ShellyCloudPlugin/plugin.py', function updateTRV
2022-01-28 21:05:19.948 Error: (RadiatoreCamera) 'onHeartbeat' failed 'KeyError'.
2022-01-28 21:05:19.948 Error: (RadiatoreCamera) ----> Line 341 in '/home/pi/domoticz/plugins/ShellyCloudPlugin/plugin.py', function onHeartbeat
2022-01-28 21:05:19.948 Error: (RadiatoreCamera) ----> Line 306 in '/home/pi/domoticz/plugins/ShellyCloudPlugin/plugin.py', function onHeartbeat
2022-01-28 21:05:19.948 Error: (RadiatoreCamera) ----> Line 712 in '/home/pi/domoticz/plugins/ShellyCloudPlugin/plugin.py', function updateTRV

**Comment by mario-peters** [comment]
The error in the onstart methode is strange. It looks like it can’t Connect To the shelly devies. Did you set the username and password in the shelly trv device?

**Comment by sandrodiscandicci** [comment]
To help you identify the problem I wanted to inform you that I have 4 Shelly devices: 1 Shelly1, 1 Shelly 2.5, 1 Shelly TRV and 1 Shelly Flood. With shelly 1 and 2.5 everything works regularly while with the TRV and the Flood I have the same errors.

**Comment by mario-peters** [comment]
hmm, I think that I know how to find your problem. Could you also send me the outcome of http://<IP address TRV>/settings

Could you create a new bug for the Flood error and insert the outcome of the http://<IP address Flood>/settings and http://<IP address Flood>/status in the new bug?

**Comment by sandrodiscandicci** [comment]
This is settings of TRV
{ "device":{"type":"SHTRV-01","mac":"60A423D3E9F2","hostname":"shellytrv-60A423D3E9F2","num_outputs":0},"wifi_ap":{"enabled":false,"ssid":"shellytrv-60A423D3E9F2"},"wifi_sta":{"enabled":true,"ssid":"casamimmi","ipv4_method":"dhcp","ip":null,"gw":null,"mask":null,"dns":null},"mqtt":{"enable":false,"server":"172.17.1.18:1883","user":"mqtt","id":"shellytrv-60A423D3E9F2","clean_session":true,"max_qos":0,"retain":false,"update_period":60},"sntp":{"server":"time.google.com","enabled":true},"login":{"enabled":true,"unprotected":false,"username":"admin","default_username":"admin"},"pin_code":"NoiafT","name":"RadiatoreCamera","fw":"20220115-083921/v2.1.2@3f3e56f8","discoverable":false,"build_info":{"build_id":"20220115-083921/v2.1.2@3f3e56f8","build_timestamp":"2022-01-15T08:39:21Z","build_version":"2022011508"},"cloud":{"enabled":true},"coiot":{"enabled":false,"update_period":3600,"peer":""},"timezone":"Europe/Rome","lat":41.959671,"lng":12.460350,"tzautodetect":true,"tz_utc_offset":3600,"tz_dst":false,"tz_dst_auto":true,"time":"17:34","child_lock":false,"display":{"brightness":1,"flipped":false},"hwinfo":{"hw_revision":"dev-prototype","batch_id":0},"sleep_mode":{"period":60,"unit":"m"},"thermostats":[{"target_t":{"enabled":true,"value":23.0,"units":"C"},"schedule":false,"schedule_profile":0,"schedule_profile_names":["Livingroom","Livingroom 1","Bedroom","Bedroom 1","Holiday"],"schedule_rules":[],"temperature_offset":0.0,"ext_t":{"enabled":false}}] }

**Comment by mario-peters** [comment]
I think I've fixed the TRV issue.
After updating the source code you should remove the current one and add a new one in the hardware screen.
As said I think it should work.
Please let me know.

**Comment by sandrodiscandicci** [comment]
Well done.... It's working.

**Comment by mario-peters** [comment]
:-) going to look at the flood issue.
will close this bug.
